baseURL = 'https://metallion.cafe/'
languageCode = 'en-us'
title = "Metallion's Cafe"
theme = 'cookbook'

[menu]
  [[menu.main]]
    name = "Metallion's Cafe"
    pre = "fas fa-home" #icon, change if you would prefer a different icon
    url = "/"
    weight = 1
